<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ContactSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $admin_user_id = 1;
        $created_at_now = Carbon::now()->format('Y-m-d H:i:s');
        $created_at_2019 = '2019-09-04 09:00:00';

        DB::table('contacts')->insert(['roepnaam' => null,              'tussenvoegsel' => null,        'achternaam' => null,           'email' => null,                    'op_mailinglijst' => true,  'mobiel' => null,            'organisatie' => 'No Limits',           'edities_meegedaan' => '2019', 'activiteit_titel' => 'Workshop Breakdance',             'notities' => null, 'user_id' => null, 'created_by' => $admin_user_id, 'last_edited_by' => null, 'created_at' => $created_at_2019,]);
        DB::table('contacts')->insert(['roepnaam' => 'Theo',            'tussenvoegsel' => null,        'achternaam' => 'Voorspuy',     'email' => null,                    'op_mailinglijst' => true,  'mobiel' => null,            'organisatie' => null,                  'edities_meegedaan' => '2019', 'activiteit_titel' => 'Dammen',                          'notities' => '2019: Dammen is leuk en je traint je hersenen ermee. Jammer dat we soms vergeten hoe leuk het is. Doe daar iets aan! Vandaag nog.', 'user_id' => null, 'created_by' => $admin_user_id, 'last_edited_by' => null, 'created_at' => $created_at_2019,]);
        DB::table('contacts')->insert(['roepnaam' => 'Dirk Jan',        'tussenvoegsel' => null,        'achternaam' => 'Drost',        'email' => null,                    'op_mailinglijst' => true,  'mobiel' => null,            'organisatie' => null,                  'edities_meegedaan' => '2019', 'activiteit_titel' => 'Beach korfbal',                   'notities' => '2019: De enige gemengde sport en dan ook nog lekker op het strand. Veel zwaarder dan men denkt.', 'user_id' => null, 'created_by' => $admin_user_id, 'last_edited_by' => null, 'created_at' => $created_at_2019,]);
        DB::table('contacts')->insert(['roepnaam' => 'Jan Derk',        'tussenvoegsel' => null,        'achternaam' => 'Meisner',      'email' => 'jmeisner@davinci.nl',   'op_mailinglijst' => true,  'mobiel' => '0634947361',    'organisatie' => 'Da Vinci College',    'edities_meegedaan' => '2019', 'activiteit_titel' => 'Stadswandeling over de wallen',   'notities' => '2019: Verken o.a. de wallen van de mooie vestingstad Gorinchem te voet. En kom dingen te weten die echt niet wist.', 'user_id' => null, 'created_by' => $admin_user_id, 'last_edited_by' => null, 'created_at' => $created_at_2019,]);
        DB::table('contacts')->insert(['roepnaam' => 'Stefanie',        'tussenvoegsel' => null,        'achternaam' => 'Wendel',       'email' => null,                    'op_mailinglijst' => true,  'mobiel' => null,            'organisatie' => 'Colours of Life',     'edities_meegedaan' => '2019', 'activiteit_titel' => 'Colours of Life',                 'notities' => '2019: Samen werken aan een kunstproduct dat we samen onthullen aan het eind van de dag', 'user_id' => null, 'created_by' => $admin_user_id, 'last_edited_by' => null, 'created_at' => $created_at_2019,]);
        DB::table('contacts')->insert(['roepnaam' => 'Jeroen',          'tussenvoegsel' => null,        'achternaam' => 'Boor',         'email' => null,                    'op_mailinglijst' => false, 'mobiel' => null,            'organisatie' => 'Da Vinci College',    'edities_meegedaan' => '2019', 'activiteit_titel' => 'Bamboe bouwen',                   'notities' => null, 'user_id' => null, 'created_by' => $admin_user_id, 'last_edited_by' => null, 'created_at' => $created_at_2019,]);
        DB::table('contacts')->insert(['roepnaam' => 'Edwin',           'tussenvoegsel' => null,        'achternaam' => 'Nuijten',      'email' => null,                    'op_mailinglijst' => true,  'mobiel' => null,            'organisatie' => null,                  'edities_meegedaan' => '2019', 'activiteit_titel' => 'Voetbal',                         'notities' => null, 'user_id' => null, 'created_by' => $admin_user_id, 'last_edited_by' => null, 'created_at' => $created_at_2019,]);
        DB::table('contacts')->insert(['roepnaam' => null,              'tussenvoegsel' => null,        'achternaam' => null,           'email' => null,                    'op_mailinglijst' => true,  'mobiel' => null,            'organisatie' => 'Fit4U',               'edities_meegedaan' => '2019', 'activiteit_titel' => null,                              'notities' => null, 'user_id' => null, 'created_by' => $admin_user_id, 'last_edited_by' => null, 'created_at' => $created_at_2019,]);
        DB::table('contacts')->insert(['roepnaam' => 'Andrea',          'tussenvoegsel' => null,        'achternaam' => 'Biesheuvel',   'email' => null,                    'op_mailinglijst' => true,  'mobiel' => null,            'organisatie' => null,                  'edities_meegedaan' => '2019', 'activiteit_titel' => 'Basic Yoga',                      'notities' => null, 'user_id' => null, 'created_by' => $admin_user_id, 'last_edited_by' => null, 'created_at' => $created_at_2019,]);
        DB::table('contacts')->insert(['roepnaam' => 'Jaenela',         'tussenvoegsel' => null,        'achternaam' => 'Dossett',      'email' => null,                    'op_mailinglijst' => true,  'mobiel' => null,            'organisatie' => null,                  'edities_meegedaan' => '2019', 'activiteit_titel' => 'Creative Dance',                  'notities' => null, 'user_id' => null, 'created_by' => $admin_user_id, 'last_edited_by' => null, 'created_at' => $created_at_2019,]);
        DB::table('contacts')->insert(['roepnaam' => 'Mark',            'tussenvoegsel' => null,        'achternaam' => 'Couwenberg',   'email' => null,                    'op_mailinglijst' => true,  'mobiel' => null,            'organisatie' => null,                  'edities_meegedaan' => '2019', 'activiteit_titel' => 'Schaken',                         'notities' => null, 'user_id' => null, 'created_by' => $admin_user_id, 'last_edited_by' => null, 'created_at' => $created_at_2019,]);
        DB::table('contacts')->insert(['roepnaam' => 'Monica',          'tussenvoegsel' => null,        'achternaam' => 'Dekker',       'email' => null,                    'op_mailinglijst' => true,  'mobiel' => null,            'organisatie' => 'Da vinci College',    'edities_meegedaan' => '2019', 'activiteit_titel' => null,                              'notities' => null, 'user_id' => null, 'created_by' => $admin_user_id, 'last_edited_by' => null, 'created_at' => $created_at_2019,]);
        DB::table('contacts')->insert(['roepnaam' => null,              'tussenvoegsel' => null,        'achternaam' => null,           'email' => null,                    'op_mailinglijst' => true,  'mobiel' => null,            'organisatie' => 'Bureau Leefstijl',    'edities_meegedaan' => '2019', 'activiteit_titel' => 'Onder invloed',                   'notities' => null, 'user_id' => null, 'created_by' => $admin_user_id, 'last_edited_by' => null, 'created_at' => $created_at_2019,]);
        DB::table('contacts')->insert(['roepnaam' => 'Nuno',            'tussenvoegsel' => 'de',        'achternaam' => 'Brito',        'email' => null,                    'op_mailinglijst' => true,  'mobiel' => null,            'organisatie' => 'Da vinci College',    'edities_meegedaan' => '2019', 'activiteit_titel' => 'Bootcamp (voor commando\'s)',     'notities' => null, 'user_id' => null, 'created_by' => $admin_user_id, 'last_edited_by' => null, 'created_at' => $created_at_2019,]);
        DB::table('contacts')->insert(['roepnaam' => 'Theo',            'tussenvoegsel' => null,        'achternaam' => 'Voorspuy',     'email' => null,                    'op_mailinglijst' => true,  'mobiel' => null,            'organisatie' => null,                  'edities_meegedaan' => '2019', 'activiteit_titel' => 'Dammen',                          'notities' => null, 'user_id' => null, 'created_by' => $admin_user_id, 'last_edited_by' => null, 'created_at' => $created_at_2019,]);
        DB::table('contacts')->insert(['roepnaam' => 'Cisca',           'tussenvoegsel' => 'den',       'achternaam' => 'Boer',         'email' => null,                    'op_mailinglijst' => true,  'mobiel' => null,            'organisatie' => null,                  'edities_meegedaan' => '2019', 'activiteit_titel' => 'Chillicious Chi Neng Qigong',     'notities' => null, 'user_id' => null, 'created_by' => $admin_user_id, 'last_edited_by' => null, 'created_at' => $created_at_2019,]);
        DB::table('contacts')->insert(['roepnaam' => 'Sybo',            'tussenvoegsel' => null,        'achternaam' => 'Bruinsma',     'email' => null,                    'op_mailinglijst' => true,  'mobiel' => null,            'organisatie' => null,                  'edities_meegedaan' => '2019', 'activiteit_titel' => 'Bordspel Go',                     'notities' => null, 'user_id' => null, 'created_by' => $admin_user_id, 'last_edited_by' => null, 'created_at' => $created_at_2019,]);
        DB::table('contacts')->insert(['roepnaam' => 'Cees',            'tussenvoegsel' => null,        'achternaam' => 'Odding',       'email' => null,                    'op_mailinglijst' => true,  'mobiel' => null,            'organisatie' => 'Da vinci College',    'edities_meegedaan' => '2019', 'activiteit_titel' => 'Rondje Gorinchem op de fiets',    'notities' => null, 'user_id' => null, 'created_by' => $admin_user_id, 'last_edited_by' => null, 'created_at' => $created_at_2019,]);
        DB::table('contacts')->insert(['roepnaam' => 'Jeroen',          'tussenvoegsel' => null,        'achternaam' => 'Schotting',    'email' => null,                    'op_mailinglijst' => true,  'mobiel' => null,            'organisatie' => null,                  'edities_meegedaan' => '2019', 'activiteit_titel' => 'Boogschieten',                    'notities' => null, 'user_id' => null, 'created_by' => $admin_user_id, 'last_edited_by' => null, 'created_at' => $created_at_2019,]);
        DB::table('contacts')->insert(['roepnaam' => 'Hans',            'tussenvoegsel' => 'van der',   'achternaam' => 'Meer',         'email' => null,                    'op_mailinglijst' => true,  'mobiel' => null,            'organisatie' => 'Da vinci College',    'edities_meegedaan' => '2019', 'activiteit_titel' => 'No music no life',                'notities' => null, 'user_id' => null, 'created_by' => $admin_user_id, 'last_edited_by' => null, 'created_at' => $created_at_2019,]);
        DB::table('contacts')->insert(['roepnaam' => 'Berna',           'tussenvoegsel' => null,        'achternaam' => 'Verstappen',   'email' => 'bverstappen@davinci.nl','op_mailinglijst' => true,  'mobiel' => null,            'organisatie' => null,                  'edities_meegedaan' => '2019', 'activiteit_titel' => 'Human mens erger je niet',        'notities' => null, 'user_id' => null, 'created_by' => $admin_user_id, 'last_edited_by' => null, 'created_at' => $created_at_2019,]);
        DB::table('contacts')->insert(['roepnaam' => 'Giany',           'tussenvoegsel' => null,        'achternaam' => 'Kuwas',        'email' => 'gkuwas@davinci.nl',     'op_mailinglijst' => true,  'mobiel' => null,            'organisatie' => null,                  'edities_meegedaan' => '2019', 'activiteit_titel' => 'Beachvolleybal',                  'notities' => null, 'user_id' => null, 'created_by' => $admin_user_id, 'last_edited_by' => null, 'created_at' => $created_at_2019,]);
        DB::table('contacts')->insert(['roepnaam' => 'Henry',           'tussenvoegsel' => 'de',        'achternaam' => 'Cock',         'email' => null,                    'op_mailinglijst' => true,  'mobiel' => null,            'organisatie' => null,                  'edities_meegedaan' => '2019', 'activiteit_titel' => 'Handbal',                         'notities' => null, 'user_id' => null, 'created_by' => $admin_user_id, 'last_edited_by' => null, 'created_at' => $created_at_2019,]);
        DB::table('contacts')->insert(['roepnaam' => 'Corien',          'tussenvoegsel' => null,        'achternaam' => 'Smits',        'email' => null,                    'op_mailinglijst' => true,  'mobiel' => null,            'organisatie' => null,                  'edities_meegedaan' => '2019', 'activiteit_titel' => 'EHBO',                            'notities' => 'Heb jij een EHBO diploma, dan maak jij misschien het verschil tussen leven en dood. Kom eens bij ons oefenen met de workshops reanimatie, AED en kleine ongevallen.', 'user_id' => null, 'created_by' => $admin_user_id, 'last_edited_by' => null, 'created_at' => $created_at_2019,]);
        DB::table('contacts')->insert(['roepnaam' => 'Monique',         'tussenvoegsel' => 'du',        'achternaam' => 'Pon',          'email' => null,                    'op_mailinglijst' => true,  'mobiel' => null,            'organisatie' => null,                  'edities_meegedaan' => '2019', 'activiteit_titel' => 'Stadsspeurtocht Memory Bricks',   'notities' => 'In Gorinchem liggen Memory Bricks (stenen met raadselachtige informatie) Ga met de groep op speurtocht naar deze stenen en bekijk de stad op een andere manier.', 'user_id' => null, 'created_by' => $admin_user_id, 'last_edited_by' => null, 'created_at' => $created_at_2019,]);
        DB::table('contacts')->insert(['roepnaam' => 'James en Sanne',  'tussenvoegsel' => null,        'achternaam' => null,           'email' => null,                    'op_mailinglijst' => true,  'mobiel' => null,            'organisatie' => 'Inspire fitness',     'edities_meegedaan' => '2019', 'activiteit_titel' => 'Inspire Fitness',                 'notities' => 'Tussen de kraampjes en achter het doel bij het voetbalveld', 'user_id' => null, 'created_by' => $admin_user_id, 'last_edited_by' => null, 'created_at' => $created_at_2019,]);
        DB::table('contacts')->insert(['roepnaam' => 'Judith',          'tussenvoegsel' => null,        'achternaam' => 'Mesker',       'email' => 'jmesker@davinci.nl',    'op_mailinglijst' => true,  'mobiel' => null,            'organisatie' => 'Da vinci College',    'edities_meegedaan' => '2019', 'activiteit_titel' => 'Zorgteam',                        'notities' => 'Onze school kent een zorgteam. Ze zijn er voor jou.\r\nMaak kennis op deze dag en vraag wat ze voor jou kunnen betekenen. Altijd handig om al wat gezichten te leren kennen.', 'user_id' => null, 'created_by' => $admin_user_id, 'last_edited_by' => null, 'created_at' => $created_at_2019,]);

        // DB::table('contacts')->insert(['roepnaam' => '', 'tussenvoegsel' => '', 'achternaam' => '', 'email' => '', 'op_mailinglijst' => true, 'mobiel' => '', 'organisatie' => '', 'edities_meegedaan' => '2019', 'activiteit_titel' => '', 'notities' => null, 'user_id' => null, 'created_by' => $admin_user_id, 'last_edited_by' => null, 'created_at' => $created_at_2019,]);
    }
}
